name: ovantica
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  flutter_animated_icons: ^1.0.1
  path_provider: ^2.1.1
  shared_preferences: ^2.2.1
  badges: ^3.1.2
  sqflite: ^2.3.0
  provider: ^6.0.5
  pinput: ^3.0.1
  form_field_validator: ^1.1.0
  phone_text_field: ^0.0.6
  http: ^0.13.6
  fluttertoast: ^8.0.3
  firebase_auth: ^4.4.2
  email_otp: ^2.0.1
  get: ^4.6.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/icons/aks.png"
    min_sdk_android: 21
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/fashion.png
    - assets/images/accessories.png
    - assets/images/laptop2.png
    - assets/images/mobile5.png
    - assets/images/watch2.png
    - assets/images/watch3.png
    - assets/images/furniture1.png
    - assets/images/laptop1.png
    - assets/images/tvs.png
    - assets/images/creditcard.png
    - assets/images/Gpay.png
    - assets/images/phonepe.png
    - assets/images/paytm.png
    - assets/images1/tv1.png
    - assets/images1/phone6.png
    - assets/images1/iphone.png
    - assets/images1/iphone1.png
    - assets/images1/laptop5.png
    - assets/images1/laptop6.png
    - assets/images1/toys2.png
    - assets/images1/offer1.png
    - assets/images1/offer2.png
    - assets/images1/fashion6.png
    - assets/icons/facebook1.png
    - assets/icons/gmail1.png
    - assets/icons/instagram1.png
    - assets/icons/phone-icon.png
    - assets/icons/twitter.png
    - assets/icons/whatsapp2.png
    - assets/icons/youtube1.png
    - assets/icons/x.png
    - assets/icons/profile1.png
    - assets/icons/about1.png
    - assets/icons/logo1.png
    - assets/images/watch.jpg
    - assets/images1/toys1.png
    - assets/images1/t-shirts1.jpg
    - assets/images/phone8.png
    - assets/images1/headset.png
    - assets/images1/headset1.png
    - assets/icons/aks.png
    - assets/icons/aks1.png
    - assets/icons/realme1.png
    - assets/icons/poco.png
    - assets/icons/samsung.png
    - assets/icons/vivo1.png
    - assets/icons/mi.png
    - assets/icons/motorola.png
    - assets/icons/infinix.png
    - assets/icons/iphonelogo.png
    - assets/icons/5g.png
    - assets/icons/oneplus.png
    - assets/icons/percentile.png
    - assets/icons/box.png
    - assets/images1/laptops1.png
    - assets/images1/laptops2.png
    - assets/images1/laptops2in1.png
    - assets/images1/laptops3.png
    - assets/images1/pc.png
    - assets/images1/tablet-min.png
    - assets/images1/tablet1-min.png
    - assets/images1/tablet3-min.png
    - assets/images1/charger.png
    - assets/images1/gamepad.png
    - assets/images1/gaming.png
    - assets/images1/keyboard.png
    - assets/images1/mouse.png
    - assets/images1/phonecover.png
    - assets/images1/router.png
    - assets/images1/selfiestick.png
    - assets/images1/ups.png
    - assets/images1/webcam.png
    - assets/images1/tvs1.png
    - assets/images1/tvs2.png
    - assets/images1/tvs3.png
    - assets/images1/airconditioner.png
    - assets/images1/cooker.png
    - assets/images1/induction.png
    - assets/images1/inverter.png
    - assets/images1/ironbox.png
    - assets/images1/mixer.png
    - assets/images1/refrigerator.png
    - assets/images1/vacuum.png
    - assets/images1/washing.png
    - assets/images1/water.png
    - assets/images1/gasstove.png
    - assets/images1/fan.png
    - assets/images1/emptybox.png
    - assets/images3/1.png
    - assets/images3/2.png
    - assets/images3/3.png
    - assets/images3/4.png
    - assets/images3/5.png
    - assets/images3/6.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
